# Generated by Django 4.0.3 on 2022-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('team', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cpu_size', models.FloatField()),
                ('memory_size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('imac_team', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='')),
                ('cpu_size', models.FloatField()),
                ('memory_size', models.FloatField()),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('name_type', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
