# Generated by Django 4.0.3 on 2022-03-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_document_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
