# Generated by Django 4.0.3 on 2022-03-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
