# Generated by Django 4.0.3 on 2022-03-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='group',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='cpu_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='memory_size',
        ),
    ]
