# Generated by Django 4.0.3 on 2022-03-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_rename_group_document_title_remove_document_cpu_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
