# Generated by Django 4.0.3 on 2022-03-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_document_cpu_size_alter_document_memory_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
