# Generated by Django 4.0.3 on 2022-03-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('cpu_size', models.FloatField()),
                ('memory_size', models.FloatField()),
            ],
        ),
    ]
