apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: iot
spec:
  containers:
  - name: ubuntu
    image: ubuntu:19.04
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "10Mi"
        cpu: "100m"
    args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']